/* Leitura financeira: mesma base, mesmo período e detalhe para cada número. */
const GESTAO_UI = (() => {
  const nomesMes=['Janeiro','Fevereiro','Março','Abril','Maio','Junho','Julho','Agosto','Setembro','Outubro','Novembro','Dezembro'];
  const abas={visao:'Resumo',lancamentos:'Lançamentos',retiradas:'Retiradas',receber:'A receber',pagar:'A pagar',contas:'Contas',conferencias:'Conferências'};
  let acoes=[],ultimaFin=null,atualizando=false;
  const base=()=>FIN_GESTAO.montar(S.reg,hojeISO());
  const estado=()=>TELAS._gestao||(TELAS._gestao={ano:hojeISO().slice(0,4),mes:'',conta:'',q:'',secao:'visao'});
  const periodo=f=>f.mes?nomesMes[Number(f.mes)-1]+' de '+f.ano:f.ano?'Ano '+f.ano:'Todo o histórico';
  const moeda=(v,tipo)=>'<span class="'+(tipo==='entrada'?'fin-entrada':tipo==='saida'?'fin-saida':v<0?'fin-saida':'fin-entrada')+'">'+fmt.brl(v)+'</span>';
  const data=d=>FIN_GESTAO.valida(d)?fmt.data(d):'Não informada';
  function acao(fn){const i=acoes.push(fn)-1;return ' data-gf-acao="'+i+'"';}
  function botao(t,fn,cls='btn'){return '<button type="button" class="'+cls+'"'+acao(fn)+'>'+t+'</button>';}
  function ligar(alvo){alvo.querySelectorAll('[data-gf-acao]').forEach(b=>{const fn=acoes[Number(b.dataset.gfAcao)];b.onclick=e=>{e.stopPropagation();fn();};});}
  function card(t,v,nota,fn,tipo){return botao('<span class="gf-rotulo">'+esc(t)+'</span><strong>'+moeda(v,tipo)+'</strong><span class="gf-nota">'+esc(nota)+'</span><span class="gf-ver">Ver lançamentos ↗</span>',fn,'gf-card');}
  function inicio(t,nota,btn=''){return '<div class="gf-titulo"><div><span class="gf-eyebrow">Portal dos Bosques · Omie</span><h2>'+esc(t)+'</h2><p>'+esc(nota)+'</p></div>'+btn+'</div>';}
  function quadro(t,nota,conteudo){return '<section class="gf-bloco"><div class="gf-subtitulo"><h3>'+esc(t)+'</h3>'+(nota?'<p>'+esc(nota)+'</p>':'')+'</div>'+conteudo+'</section>';}
  function vazio(t){return '<div class="gf-vazio">'+esc(t)+'</div>';}
  function avisos(b){
    const ds=b.movimentos.map(x=>x.data).sort(),f=estado(),tem=FIN_GESTAO.filtrar(b.movimentos,f).length;
    return '<div class="gf-origem"><span class="gf-ponto"></span><span><b>Base: movimentações bancárias do Omie</b><br>'+(ds.length?'Histórico importado de '+data(ds[0])+' a '+data(ds.at(-1))+'.':'Nenhuma movimentação bancária importada nesta leitura.')+'</span><span class="gf-cor-legend"><span class="fin-entrada">● Entradas</span><span class="fin-saida">● Saídas</span></span></div>'+(!tem?'<p class="gf-alerta">Sem movimentações importadas em '+esc(periodo(f))+'. Isso não comprova ausência de movimentação no Omie.</p>':'');
  }
  function filtros(b,renderizar){
    const f=estado(),anos=[...new Set(['2025',hojeISO().slice(0,4),f.ano,...b.bancos.map(x=>x.data.slice(0,4)).filter(x=>/^\d{4}$/.test(x))])].filter(Boolean).sort().reverse();
    const contas=[...new Map(b.bancos.map(x=>[x.conta,x.contaNome])).entries()];
    return '<section class="gf-filtros" aria-label="Período da consulta"><div class="gf-filtro-linha"><label>Ano<select id="gf-ano">'+anos.map(a=>'<option value="'+a+'"'+(a===f.ano?' selected':'')+'>'+a+'</option>').join('')+'</select></label><label>Conta<select id="gf-conta"><option value="">Todas as contas</option>'+contas.map(([id,n])=>'<option value="'+esc(id)+'"'+(id===f.conta?' selected':'')+'>'+esc(n)+'</option>').join('')+'</select></label><div class="gf-periodo"><b>'+esc(periodo(f))+'</b><span>'+(renderizar===financeiro&&['receber','pagar'].includes(f.secao)?'Pela data do vencimento':!f.mes||f.ano+f.mes<=hojeISO().slice(0,4)+hojeISO().slice(5,7)?'Realizado pela data do pagamento':'Período futuro')+'</span></div>'+botao('Atualizar dados',()=>atualizar(renderizar),'btn gf-atualizar')+'</div><div class="gf-meses" role="group" aria-label="Selecionar mês">'+[['','Ano todo'],...nomesMes.map((n,i)=>[String(i+1).padStart(2,'0'),n.slice(0,3)])].map(([m,n])=>'<button type="button" class="'+(f.mes===m?'on':'')+'" aria-pressed="'+(f.mes===m)+'"'+acao(()=>{f.mes=m;f.q='';renderizar();})+'>'+n+'</button>').join('')+'</div></section>';
  }
  function ligarFiltros(renderizar){const f=estado();const ano=document.getElementById('gf-ano'),conta=document.getElementById('gf-conta');if(ano)ano.onchange=()=>{f.ano=ano.value;renderizar();};if(conta)conta.onchange=()=>{f.conta=conta.value;renderizar();};}
  async function atualizar(renderizar){
    if(atualizando)return;atualizando=true;const bot=document.querySelector('.gf-atualizar');if(bot){bot.disabled=true;bot.textContent='Atualizando…';}
    try{if(!navigator.onLine)throw new Error('Sem conexão. Os dados salvos continuam disponíveis.');
      await apiOmie('referencias');
      const limite=Date.now()+60000;
      while(typeof _puxando!=='undefined'&&_puxando){if(Date.now()>limite)throw new Error('A leitura em andamento ainda não terminou. Aguarde o indicador de atualização.');await new Promise(r=>setTimeout(r,250));}
      await puxar();if(S.erroSync)throw new Error(S.erroSync);
      renderizar();toast('Dados do servidor atualizados. A busca no Omie continua automática.');
    }catch(e){toast(e.message||'Não foi possível atualizar agora.','ruim');}
    finally{atualizando=false;const b=document.querySelector('.gf-atualizar');if(b){b.disabled=false;b.textContent='Atualizar dados';}}
  }
  function nav(){const f=estado();return '<nav class="gf-nav" aria-label="Consultas financeiras">'+Object.entries(abas).map(([k,n])=>'<button type="button" aria-current="'+(f.secao===k?'page':'false')+'"'+acao(()=>{f.secao=k;f.q='';f.tipo='';f.pagina=0;financeiro();})+'>'+n+'</button>').join('')+'</nav>';}
  function exportarLista(t,itens){PDF.gestao({titulo:t,periodo:contextoLista(itens),itens},S.cfg||{});toast('PDF gerado com todos os lançamentos deste recorte.');}
  function contextoLista(itens){const ds=itens.map(x=>x.data).filter(FIN_GESTAO.valida).sort();return ds.length?data(ds[0])+' a '+data(ds.at(-1)):'Nenhum lançamento';}
  function listaHtml(itens,pagina=0){const vis=itens.slice(pagina*40,pagina*40+40);return '<div class="gf-tabela-scroll"><table class="gf-tabela"><thead><tr><th>Data</th><th>Cliente / favorecido e lançamento</th><th>Categoria</th><th class="num">Valor</th></tr></thead><tbody>'+vis.map(x=>'<tr><td>'+esc(data(x.data))+'</td><td>'+botao(esc(x.pessoa)+'<small>'+esc(x.descricao)+'</small>',()=>detalhe(x),'gf-link gf-pessoa')+'<small>'+(x.entrada?'Entrada · ':'Saída · ')+esc(x.situacao)+(x.parcial?' · parcela do rateio':'')+'</small></td><td>'+esc(x.categoria)+'</td><td class="num">'+botao(moeda(x.valor,x.situacao==='Vencido'?'saida':x.entrada?'entrada':'saida'),()=>detalhe(x),'gf-link')+'</td></tr>').join('')+'</tbody></table></div>'+(itens.length?'':vazio('Nenhum lançamento neste recorte.'));}
  function abrirLista(t,itens,pagina=0){
    const ordenados=[...itens].sort((a,b)=>b.data.localeCompare(a.data)||String(a.id).localeCompare(String(b.id))),r=FIN_GESTAO.resumo(itens),pg=Math.max(0,Math.min(pagina,Math.ceil(itens.length/40)-1));
    const modal=abrirModal({titulo:t,largo:true,corpo:'<p class="gf-lista-contexto">'+esc(contextoLista(itens))+' · '+itens.length+' lançamentos · todos os valores abaixo pertencem a este recorte.</p><div class="gf-mini-totais"><span>Entradas '+moeda(r.entradas,'entrada')+'</span><span>Saídas '+moeda(r.saidas,'saida')+'</span></div>'+listaHtml(ordenados,pg)+'<p class="nota">Página '+(pg+1)+' de '+Math.max(1,Math.ceil(itens.length/40))+'. O PDF inclui todas as páginas.</p>',acoes:[{texto:'Fechar',aoClicar:fecharModal},{texto:'Baixar PDF',aoClicar:()=>exportarLista(t,itens)},...(pg?[{texto:'Anterior',aoClicar:()=>{fecharModal();abrirLista(t,itens,pg-1);}}]:[]),...((pg+1)*40<itens.length?[{texto:'Próxima',aoClicar:()=>{fecharModal();abrirLista(t,itens,pg+1);}}]:[])]});ligar(modal);
  }
  function detalhe(x){
    const ref=x.ref||{},linha=(n,v)=>'<div><dt>'+esc(n)+'</dt><dd>'+esc(v||'Não informado')+'</dd></div>';
    const valor=moeda(x.valor,x.situacao==='Vencido'?'saida':x.entrada?'entrada':'saida');
    const conteudo='<div class="gf-detalhe-valor">'+valor+'<small>'+esc(x.situacao)+'</small></div><dl class="gf-detalhe">'+linha(x.entrada?'Cliente':'Favorecido',x.pessoa)+linha('Descrição',x.descricao)+linha('Categoria no Omie',x.categoria)+linha('Conta',x.contaNome)+linha('Documento',ref.documento)+linha('Título Omie',x.titulo)+linha('Data usada no período',data(x.data))+linha('Pagamento',data(FIN_GESTAO.data(ref.dataPagamento)))+linha('Crédito em conta',data(FIN_GESTAO.data(ref.dataCredito)))+linha('Vencimento',data(FIN_GESTAO.data(ref.dataVencimento)))+linha('Emissão',data(FIN_GESTAO.data(ref.dataEmissao)))+'</dl><p class="nota">'+(x.pendente?'Conta ainda em aberto, pela data de vencimento. Não compõe o dinheiro já movimentado.':'Os meses usam a data do pagamento no Omie. Emissão, vencimento e crédito podem ser diferentes.')+'</p>'+quadro('Centro de custos','Distribuição do valor exibido; informações não identificadas ficam sinalizadas.',FIN_GESTAO.fatias(x,'centros').map(p=>'<p>'+esc(p.nome)+' · '+moeda(p.valor,x.entrada?'entrada':'saida')+'</p>').join(''))+(x.parcial?'<p class="gf-alerta">Este recorte mostra uma parcela do rateio. Valor total do movimento original: '+esc(fmt.brl(x.valorOriginal||x.valor))+'.</p>':'');
    abrirModal({titulo:'Detalhes do lançamento',corpo:conteudo,largo:true,acoes:[{texto:'Voltar',aoClicar:fecharModal},...(x.vendaId?[{texto:'Abrir venda',aoClicar:()=>{fecharModal();location.hash='#/venda/'+x.vendaId;}}]:[]),...(x.locais?.length===1?[{texto:'Conferir vínculo local',aoClicar:()=>{const l=x.locais[0];l.col==='rec'?finEditarRecebimento(l,()=>render()):abrirEdicaoLancamento(l.id,()=>render());}}]:[])]});
  }
  function kpis(itens,titulo=''){const r=FIN_GESTAO.resumo(itens);return '<div class="gf-cards">'+card('Entrou',r.entradas,'Recebido no período',()=>abrirLista(titulo+' · Entradas',itens.filter(x=>x.entrada)),'entrada')+card('Saiu',r.saidas,'Pago no período',()=>abrirLista(titulo+' · Saídas',itens.filter(x=>!x.entrada)),'saida')+card('Resultado dos movimentos',r.resultado,'Entradas menos saídas; não é saldo bancário',()=>abrirLista(titulo+' · Todos os movimentos',itens))+'</div>';}
  function grupos(t,itens,campo,tipo='saida'){
    const gs=FIN_GESTAO.agrupar(itens,campo);const total=FIN_GESTAO.resumo(itens),max=Math.max(1,...gs.map(g=>g.saidas+g.entradas));
    return quadro(t,'Clique em uma linha para abrir os lançamentos que compõem o valor.',gs.length?'<div class="gf-grupos">'+gs.map((g,i)=>(i===6?'<details class="gf-mais"><summary>Ver mais '+(gs.length-6)+' grupos</summary>':'')+botao('<span><b>'+esc(g.nome)+'</b><small>'+g.itens.length+' lançamentos</small><i style="--gf-largura:'+((g.entradas+g.saidas)/max*100)+'%"></i></span><strong>'+moeda(tipo==='entrada'?g.entradas:g.saidas,tipo)+'</strong><span aria-hidden="true">↗</span>',()=>abrirLista(t+' · '+g.nome,g.itens),'gf-grupo')).join('')+(gs.length>6?'</details>':'')+'</div>'+botao('Total · '+moeda(tipo==='entrada'?total.entradas:total.saidas,tipo),()=>abrirLista(t,itens),'gf-total'):vazio('Nenhum lançamento neste período.'));
  }
  function mensal(b,itens,ano){
    const ms=FIN_GESTAO.meses(FIN_GESTAO.filtrar(itens,{conta:estado().conta}),ano),max=Math.max(1,...ms.flatMap(m=>[m.entradas,m.saidas]));
    return quadro('Mês a mês · '+ano,'Clique no mês ou em um valor para ver os lançamentos exatos.','<div class="gf-grafico" aria-label="Entradas e saídas mensais">'+ms.map(m=>botao('<span class="gf-barras"><i class="gf-barra-entrada" style="height:'+m.entradas/max*100+'%"></i><i class="gf-barra-saida" style="height:'+m.saidas/max*100+'%"></i></span><span>'+nomesMes[Number(m.mes.slice(5))-1].slice(0,3)+'</span>',()=>abrirLista('Movimentações · '+nomeMes(m.mes),m.itens),'gf-grafico-mes')).join('')+'</div><div class="gf-tabela-scroll"><table class="gf-tabela"><thead><tr><th>Mês</th><th class="num">Entrou</th><th class="num">Saiu</th><th class="num">Resultado</th><th class="num">Lançamentos</th></tr></thead><tbody>'+ms.map(m=>'<tr'+(estado().mes===m.mes.slice(5)?' class="gf-selecionado"':'')+'><th>'+botao(nomesMes[Number(m.mes.slice(5))-1],()=>abrirLista(nomeMes(m.mes),m.itens),'gf-link')+'<small>'+esc(relSituacaoMes(m.mes,m.quantidade))+'</small></th>'+[['entradas','entrada'],['saidas','saida'],['resultado','']].map(([k,t])=>'<td class="num">'+botao(moeda(m[k],t),()=>abrirLista(nomeMes(m.mes)+' · '+(t==='entrada'?'Entradas':t==='saida'?'Saídas':'Movimentos'),t?m.itens.filter(x=>x.entrada===(t==='entrada')):m.itens),'gf-link')+'</td>').join('')+'<td class="num">'+botao(String(m.quantidade),()=>abrirLista(nomeMes(m.mes),m.itens),'gf-link')+'</td></tr>').join('')+'</tbody></table></div>');
  }
  function proximos(b){const itens=FIN_GESTAO.filtrar(b.abertos,{conta:estado().conta}),r=FIN_GESTAO.resumo(itens),vencidos=itens.filter(x=>x.situacao==='Vencido');return quadro('Contas ainda em aberto','Saldos dos títulos no Omie, em todos os vencimentos. Não entram no resultado realizado.','<div class="gf-cards">'+card('A receber',r.entradas,'Parcelas vencidas e futuras',()=>abrirLista('Contas a receber',itens.filter(x=>x.entrada)),'entrada')+card('A pagar',r.saidas,'Compromissos ainda não pagos',()=>abrirLista('Contas a pagar',itens.filter(x=>!x.entrada)),'saida')+card('Vencido a receber',FIN_GESTAO.resumo(vencidos).entradas,'Parcelas para acompanhar',()=>abrirLista('Vencido a receber',vencidos.filter(x=>x.entrada)),'saida')+'</div>');}
  function listaTela(itens,f,t){const filtrados=FIN_GESTAO.filtrar(itens,{q:f.q}),pg=Math.max(0,Math.min(f.pagina||0,Math.ceil(filtrados.length/40)-1));return quadro(t,filtrados.length+' lançamentos no recorte.','<div class="gf-lista-acoes"><label>Buscar por nome, documento ou categoria<input id="gf-busca" type="search" value="'+esc(f.q||'')+'" placeholder="Digite para encontrar um lançamento"></label>'+botao('PDF deste recorte',()=>exportarLista(t,filtrados))+'</div>'+listaHtml([...filtrados].sort((a,b)=>b.data.localeCompare(a.data)),pg)+'<div class="gf-paginas">'+(pg?botao('Anterior',()=>{f.pagina=pg-1;financeiro();}):'')+'<span>Página '+(pg+1)+' de '+Math.max(1,Math.ceil(filtrados.length/40))+'</span>'+((pg+1)*40<filtrados.length?botao('Próxima',()=>{f.pagina=pg+1;financeiro();}):'')+'</div>');}
  function retiradas(b,itens){const rs=FIN_GESTAO.filtrar(b.retiradas,estado()),possiveis=FIN_GESTAO.filtrar(b.possiveis,estado());return quadro('Retiradas e movimentações dos sócios','Valores identificados pela categoria do Omie. Mútuos, pró-labore e distribuição de lucros mantêm suas classificações.',kpis(rs,'Sócios')+(!rs.length?vazio('Nenhuma retirada identificada pela categoria neste período. Use a consulta por favorecido abaixo para conferir os pagamentos.'):''))+'<div class="gf-duas-colunas">'+grupos('Saídas por natureza',rs.filter(x=>!x.entrada),'categorias')+grupos('Saídas por sócio / favorecido',rs.filter(x=>!x.entrada),'pessoa')+'</div>'+(possiveis.length?quadro('Descrição a conferir','O texto sugere movimentação de sócio, mas a categoria não confirma. Fora dos totais de retiradas.',botao('Conferir '+possiveis.length+' lançamentos',()=>abrirLista('Possíveis retiradas · conferir categoria',possiveis))):'')+grupos('Todos os pagamentos por favorecido',itens.filter(x=>!x.entrada),'pessoa');}
  function conferencias(b){const locais=b.locais;return quadro('Atualização do Omie','Acompanhe a última conclusão e a busca automática de novos dados.','<p id="gf-sync" class="nota">Consultando a integração…</p>')+quadro('Conferências da base','As verificações ficam aqui para manter a leitura do resultado mais direta.','<div class="gf-consultas">'+botao('<b>Datas e valores a conferir</b><span>'+b.excluidos.length+' movimentos fora dos totais realizados</span>',()=>abrirLista('Movimentos com data futura ou inválida',b.excluidos),'gf-consulta')+botao('<b>Diferenças com o Omie</b><span>Comparar títulos e registros locais</span>',()=>abrirConferencia('diferencas'),'gf-consulta')+botao('<b>Vínculos e cadastros</b><span>Ver pagamentos, parcelas e classificações pendentes</span>',()=>abrirConferencia('pendencias'),'gf-consulta')+botao('<b>Registros locais sem vínculo Omie</b><span>'+locais.length+' registros preservados, fora dos totais bancários</span>',()=>{const ctx=finIndices();abrirOperacionais('Registros locais',finDiferencas(ctx).filter(x=>x.id.startsWith('manual-')));},'gf-consulta')+'</div>');}
  function abrirOperacionais(t,itens,pg=0){const vis=itens.slice(pg*40,pg*40+40);const m=abrirModal({titulo:t,largo:true,corpo:'<p>'+itens.length+' verificações. Não representam dívida adicional.</p>'+vis.map(x=>botao('<span><b>'+esc(x.descricao)+'</b><small>'+esc(x.situacao)+'</small></span><span>'+finValor(x.valor,finCor(x))+'</span>',()=>finAbrirLinha(x),'gf-grupo')).join(''),acoes:[{texto:'Fechar',aoClicar:fecharModal},...(pg?[{texto:'Anterior',aoClicar:()=>{fecharModal();abrirOperacionais(t,itens,pg-1);}}]:[]),...((pg+1)*40<itens.length?[{texto:'Próxima',aoClicar:()=>{fecharModal();abrirOperacionais(t,itens,pg+1);}}]:[])]});ligar(m);}
  function abrirConferencia(aba){const ctx=finIndices(),ls=finLinhas(aba,ctx).map(x=>finEnriquecer(x,ctx));abrirOperacionais(aba==='pendencias'?'Vínculos para conferir':'Diferenças com Omie',ls);}
  function contas(b,itens){const ls=FIN_GESTAO.filtrar(b.bancos.filter(x=>FIN_GESTAO.valida(x.data)&&x.data<=b.hoje),estado()),gs=FIN_GESTAO.agrupar(ls,'contaNome');return quadro('Movimentação por conta','Entradas e saídas do período. Estes valores não comprovam o saldo disponível hoje.',gs.map(g=>'<div class="gf-conta"><h4>'+esc(g.nome)+'</h4>'+kpis(g.itens,g.nome)+'</div>').join('')||vazio('Nenhuma conta com movimentação importada.'))+quadro('Transferências entre contas','Não compõem entradas, saídas e resultado dos relatórios.',botao('Conferir transferências · '+FIN_GESTAO.filtrar(b.transferencias,estado()).length+' movimentos',()=>abrirLista('Transferências entre contas',FIN_GESTAO.filtrar(b.transferencias,estado()))))+quadro('Saldo consultado no Omie','Consulta separada dos movimentos do período.','<div id="gf-saldos">'+botao('Consultar saldo atual',async()=>{const e=document.getElementById('gf-saldos');e.textContent='Consultando…';try{const r=await saldoBancosOmie();e.innerHTML='<p>'+esc(fmt.quando(r.quando))+(r.parcial?' · Consulta parcial':'')+'</p>'+(r.contas||[]).map(c=>'<p>'+esc(c.nome)+' · '+(c.saldo==null?'Saldo indisponível':moeda(c.saldo))+'</p>').join('');}catch(err){e.textContent=err.message||'Consulta indisponível.';}})+'</div>');}
  function adotarLegado(){const l=TELAS._fin,f=estado();if(l&&l!==ultimaFin){ultimaFin=l;f.secao=({recebimentos:'lancamentos',despesas:'lancamentos',pendencias:'conferencias',diferencas:'conferencias',centros:'centros'})[l.aba]||l.aba||'visao';f.tipo=l.aba==='recebimentos'?'entrada':l.aba==='despesas'?'saida':'';if(l.ano)f.ano=l.ano;f.mes=l.mes||'';f.q=l.q||'';}}
  function financeiro(){adotarLegado();const f=estado();if(f.secao!=='lancamentos')f.tipo='';if(f.secao==='centros'){centros();return;}acoes=[];const b=base(),itens=FIN_GESTAO.filtrar(b.movimentos,f),renderizar=financeiro;let html=inicio('Entradas, saídas e retiradas','Escolha o período. Clique nos valores para entender cada entrada e saída.')+nav()+filtros(b,renderizar)+avisos(b);
    if(f.secao==='visao'){html+=kpis(itens,periodo(f))+quadro('Acessos rápidos','', '<div class="gf-consultas">'+botao('<b>Retiradas dos sócios</b><span>Por pessoa e por natureza →</span>',()=>{f.secao='retiradas';f.tipo='';financeiro();},'gf-consulta')+botao('<b>Relatórios mensais</b><span>Comparar meses e categorias →</span>',()=>{location.hash='#/relatorios';},'gf-consulta')+botao('<b>Centro de custos</b><span>Entender onde o dinheiro foi usado →</span>',()=>{location.hash='#/centros';},'gf-consulta')+'</div>')+mensal(b,b.movimentos,f.ano)+proximos(b);}
    else if(f.secao==='lancamentos'){html+=kpis(itens,'Lançamentos')+'<div class="gf-tipos">'+[['','Tudo'],['entrada','Só entradas'],['saida','Só saídas']].map(([v,n])=>botao(n,()=>{f.tipo=v;f.pagina=0;financeiro();},'btn '+(f.tipo===v?'primario':''))).join('')+'</div>'+listaTela(itens,f,'Lançamentos do período');}
    else if(f.secao==='retiradas')html+=retiradas(b,itens);
    else if(['receber','pagar'].includes(f.secao)){const entrada=f.secao==='receber',todos=b.abertos.filter(x=>x.entrada===entrada),ls=FIN_GESTAO.filtrar(todos,{...f,tipo:'',q:''});html+=quadro(entrada?'Contas a receber':'Contas a pagar','O período filtra a data de vencimento. Os valores são saldos ainda abertos no Omie.','<div class="gf-cards">'+['Vencido','Vence hoje','A vencer'].map(s=>{const vs=ls.filter(x=>x.situacao===s);return card(s,vs.reduce((a,x)=>a+FIN_GESTAO.cent(x.valor),0)/100,vs.length+' títulos no período',()=>abrirLista(s,vs),s==='Vencido'?'saida':entrada?'entrada':'saida');}).join('')+'</div>'+botao('Ver todos os vencimentos · '+todos.length+' títulos',()=>abrirLista('Todos os vencimentos',todos)))+listaTela(ls,f,entrada?'Títulos a receber':'Títulos a pagar');}
    else if(f.secao==='conferencias')html+=conferencias(b);
    else if(f.secao==='contas')html+=contas(b,itens);
    document.getElementById('app').innerHTML='<div class="gf">'+html+'</div>';ligar(document.getElementById('app'));ligarFiltros(renderizar);
    const sync=document.getElementById('gf-sync');if(sync)statusOmieHome(sync);
    const busca=document.getElementById('gf-busca');if(busca)busca.oninput=()=>{f.q=busca.value;f.pagina=0;clearTimeout(_finBuscaTimer);_finBuscaTimer=setTimeout(()=>vdRenderComFoco(financeiro),220);};
  }
  function relatorios(){if(TELAS._relMes){estado().ano=TELAS._relMes.slice(0,4);estado().mes=TELAS._relMes.slice(5);TELAS._relMes='';}acoes=[];const b=base(),f=estado(),itens=FIN_GESTAO.filtrar(b.movimentos,{...f,tipo:'',q:''}),renderizar=relatorios;const btn=botao('Baixar relatório em PDF',()=>PDF.gestao({titulo:'Relatório financeiro',periodo:periodo(f),itens,meses:FIN_GESTAO.meses(FIN_GESTAO.filtrar(b.movimentos,{conta:f.conta}),f.ano),categorias:FIN_GESTAO.agrupar(itens.filter(x=>!x.entrada),'categorias')},S.cfg||{}),'btn primario');
    document.getElementById('app').innerHTML='<div class="gf">'+inicio('Relatórios que explicam os números','Meses, categorias e favorecidos com acesso aos lançamentos.',btn)+filtros(b,renderizar)+avisos(b)+kpis(itens,'Resultado do período')+mensal(b,b.movimentos,f.ano)+'<div class="gf-duas-colunas">'+grupos('De onde vieram as entradas',itens.filter(x=>x.entrada),'categorias','entrada')+grupos('Para onde foram as saídas',itens.filter(x=>!x.entrada),'categorias')+'</div>'+quadro('Retiradas no período','Saídas identificadas pelas categorias de sócios do Omie.',kpis(FIN_GESTAO.filtrar(b.retiradas,{...f,tipo:'',q:''}),'Movimentações de sócios')+botao('Detalhar retiradas por pessoa',()=>{f.secao='retiradas';f.tipo='';location.hash='#/financeiro';}))+'<div class="gf-duas-colunas">'+grupos('Saídas por centro de custo',itens.filter(x=>!x.entrada),'centros')+grupos('Maiores pagamentos por favorecido',itens.filter(x=>!x.entrada),'pessoa')+'</div>'+proximos(b)+ '</div>';ligar(document.getElementById('app'));ligarFiltros(renderizar);
  }
  function centros(){acoes=[];const b=base(),f=estado(),itens=FIN_GESTAO.filtrar(b.movimentos,{...f,tipo:'saida',q:''});document.getElementById('app').innerHTML='<div class="gf">'+inicio('Centro de custos','Acompanhe os gastos pelos lançamentos e categorias do Omie.',botao('PDF dos custos',()=>PDF.gestao({titulo:'Centro de custos',periodo:periodo(f),itens,grupoTitulo:'Saídas por centro de custo',categorias:FIN_GESTAO.agrupar(itens,'centros')},S.cfg||{})))+filtros(b,centros)+avisos(b)+'<div class="gf-cards">'+card('Total pago no período',FIN_GESTAO.resumo(itens).saidas,itens.length+' saídas do Omie',()=>abrirLista('Custos pagos',itens),'saida')+card('Sem centro identificado',FIN_GESTAO.agrupar(itens,'centros').find(g=>g.nome==='Sem centro de custo')?.saidas||0,'Conferir a classificação no lançamento',()=>abrirLista('Sem centro de custo',FIN_GESTAO.agrupar(itens,'centros').find(g=>g.nome==='Sem centro de custo')?.itens||[]),'saida')+'</div><div class="gf-duas-colunas">'+grupos('Gastos por centro de custo',itens,'centros')+grupos('Gastos por categoria',itens,'categorias')+'</div>'+mensal(b,b.movimentos.filter(x=>!x.entrada),f.ano)+'</div>';ligar(document.getElementById('app'));ligarFiltros(centros);}
  return {financeiro,relatorios,centros,base,abrirLista};
})();
TELAS.financeiro=GESTAO_UI.financeiro;
TELAS.relatorios=GESTAO_UI.relatorios;
TELAS.centros=GESTAO_UI.centros;
TELAS.cronograma=GESTAO_UI.centros;
TELAS.caixa=()=>{TELAS._fin={aba:'visao',ano:TELAS._mesCaixa?.slice(0,4)||hojeISO().slice(0,4),mes:TELAS._mesCaixa?.slice(5)||''};GESTAO_UI.financeiro();};
TELAS.lancamentos=()=>{const f=TELAS._fLanc||{};TELAS._fin={aba:f.tipo==='entrada'?'recebimentos':f.tipo==='saida'?'despesas':'lancamentos',ano:f.ano||f.mes?.slice(0,4)||hojeISO().slice(0,4),mes:/^\d{4}-\d{2}$/.test(f.mes||'')?f.mes.slice(5):'',q:f.q||''};GESTAO_UI.financeiro();};
