const fs=require('fs'),vm=require('vm'),assert=require('assert/strict'),ts=require((process.env.BSQ_TEST_DEPS || '../seed/devtools')+'/node_modules/typescript');
const clone=x=>JSON.parse(JSON.stringify(x));const registros=new Map(),metas=new Map();let handler,numero=0;let completa=true;const requisicoes=[];
const key=(c,id)=>c+'|'+id;
registros.set(key('venda','v1'),{id:'v1',clienteId:'123',parcelas:[{tid:1,valor:625,venc:'2026-09-20',conferir:false}]});
registros.set(key('cliente','777'),{id:'777',nome:'Nome editado',email:'manual@example.invalid',atualizadoPor:'Operador'});
registros.set(key('cx','manual'),{id:'manual',tipo:'saida',valor:100,data:'2026-09-05'});
const cfg={omie:{corteEntradas:'2026-01-01'}};
const dados={agora:()=>new Date().toISOString(),lerCfgBruta:async()=>clone(cfg),lerColecaoBruta:async c=>[...registros].filter(([k])=>k.startsWith(c+'|')).map(([,r])=>({registro:clone(r)})),lerUm:async(c,id)=>registros.has(key(c,id))?clone(registros.get(key(c,id))):null,
 gravarUm:async(c,id,r)=>registros.set(key(c,id),clone(r)),gravarVarios:async xs=>{for(const x of xs)registros.set(key(x.colecao,x.id),clone(x.registro));},marcarMudanca:async()=>{},registrarLog:async()=>{},guardarIndiceNumero:async()=>{},proximoNumero:async()=>++numero,
 db:{rpc:async(nome,p)=>nome==='bsq_omie_reservar'?{data:{adquirido:true,inicio:new Date().toISOString(),pagina:1,parcial:{},completa:p.p_completa,lease:'teste'}}:nome==='bsq_omie_finalizar'?{data:true}:{data:{vendasNovas:0,pagamentosVinculados:0}},from:()=>({select(){return this},eq(k,v){this.k=v;return this},maybeSingle:async function(){return {data:metas.has(this.k)?{valor:clone(metas.get(this.k))}:null}},upsert:async function(x){metas.set(x.chave,clone(x.valor));return{error:null}},delete(){return this}})}};
let movimentos=[{detalhes:{nCodTitulo:1,cGrupo:'CONTA_A_RECEBER',cStatus:'RECEBIDO',nValorTitulo:625,cCPFCNPJCliente:'123',dDtVenc:'20/09/2026',dDtPagamento:'05/09/2026'},resumo:{cLiquidado:'S',nValPago:625,nValLiquido:500,nDesconto:125,nValAberto:0}}, {detalhes:{nCodTitulo:2,cGrupo:'CONTA_A_PAGAR',cStatus:'PAGO',nValorTitulo:100,dDtPagamento:'05/09/2026'},resumo:{cLiquidado:'S',nValPago:100}}];
const ctx={console,Request,Response,Date,Map,Set,JSON,Number,String,Object,Math,Promise,Deno:{env:{get:()=> 'token'},serve:f=>handler=f},exports:{},fetch:async(_u,o)=>{const b=JSON.parse(o.body);requisicoes.push(b);return new Response(JSON.stringify(b.call==='ListarClientes'?{clientes_cadastro:[{cnpj_cpf:"987",razao_social:"Novo cliente",tags:[{tag:"Cliente"}],email:"novo@example.invalid"},{cnpj_cpf:"777",razao_social:"Nome do Omie",email:"omie@example.invalid",tags:[{tag:"Cliente"}]},{cnpj_cpf:"888",razao_social:"Fornecedor",tags:[{tag:"Fornecedor"}]}],total_de_paginas:1}:{nTotPaginas:1,movimentos}),{status:200})},require:p=>p.includes('dados')?dados:p.includes('cors')?{json:(b,s=200)=>new Response(JSON.stringify(b),{status:s}),preflight:()=>null}:{identificar:async()=>({perfil:'direcao',proprio:true,nome:'Teste'}),perfilDe:q=>q.perfil}};
vm.createContext(ctx);vm.runInContext(ts.transpileModule(fs.readFileSync('supabase/functions/bsq-omie/index.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,ctx);
const sync=async()=>{const r=await handler(new Request('https://teste.invalid',{method:'POST',headers:{'x-token':'token'},body:JSON.stringify({action:'sincronizar',completa})}));const b=await r.json();assert.equal(r.status,200,JSON.stringify(b));return b;};
(async()=>{await sync();assert.equal(registros.get('rec|rbomie-1').valor,500);assert.ok(!registros.has('cx|cxomie-2'));assert.ok(registros.has('titulo|CONTA_A_PAGAR-2'));assert.ok(registros.has('cx|manual'));assert.ok(metas.get('omie_sync').pendencias.some(p=>p.tipo==='possivel_duplicidade'));console.log('OK movimento igual preservado para conciliação sem duplicar caixa');registros.get('titulo|CONTA_A_PAGAR-2').decisaoDuplicidade='distintos';
await sync();assert.equal([...registros.keys()].filter(k=>k.startsWith('rec|')).length,1);console.log('OK repetição idempotente');
movimentos[0].resumo.nJuros=20;movimentos[0].resumo.nValLiquido=520;await sync();assert.equal(registros.get('rec|rbomie-1').valor,520);assert.equal(registros.get('rec|rbomie-1').omie.original.resumo.nValPago,625);console.log('OK valor líquido inclui desconto e juros preservando o principal');
const core=require('../financeiro-core.js');assert.equal(core.resumo(registros.get('venda|v1'),[registros.get('rec|rbomie-1')],'2026-10-01').saldo,0);console.log('OK encargos de parcela quitada não viram atraso');
movimentos[0].detalhes.cStatus='CANCELADO';movimentos[1].detalhes.cStatus='CANCELADO';await sync();assert.ok(registros.get('rec|rbomie-1').apagadoEm);assert.ok(registros.get('cx|cxomie-2').apagadoEm);console.log('OK estorno de receita e despesa');
movimentos=[{detalhes:{nCodTitulo:99,cGrupo:'CONTA_A_RECEBER',cCPFCNPJCliente:'123',cStatus:'ABERTO',nValorTitulo:625,dDtVenc:'20/10/2026'},resumo:{nValPago:0,nValAberto:625}}];await sync();assert.ok(registros.has('titulo|CONTA_A_RECEBER-99'));assert.ok(!registros.get('venda|v1').parcelas.some(p=>p.tid===99));assert.ok(metas.get('omie_sync').pendencias.some(p=>p.titulo===99));console.log('OK título novo preservado sem vínculo inventado');
assert.equal(registros.get('cliente|777').email,'manual@example.invalid');assert.equal(registros.get('cliente|777').nome,'Nome editado');assert.equal(registros.get('cliente|987').nome,'Novo cliente');assert.equal(registros.get('cliente|987').email,'novo@example.invalid');assert.ok(!registros.has('cliente|888'));assert.equal([...registros.keys()].filter(k=>k==='cliente|987').length,1);console.log('OK cliente novo criado sem duplicar e fornecedor não importado como cliente');
cfg.omie.corteEntradas='2025-01-01';completa=false;requisicoes.length=0;
movimentos=[{detalhes:{nCodTitulo:2025,cGrupo:'CONTA_A_RECEBER',cCPFCNPJCliente:'123',cStatus:'RECEBIDO',nValorTitulo:300,dDtVenc:'10/12/2025',dDtPagamento:'10/12/2025'},resumo:{nValPago:300,nValLiquido:300,nValAberto:0,cLiquidado:'S'}}];
await sync();assert.equal(requisicoes.find(r=>r.call==='ListarMovimentos').param[0].dDtAltDe,undefined);assert.equal(registros.get('rec|rbomie-2025').valor,300);assert.equal(registros.get('rec|rbomie-2025').data,'2025-12-10');
requisicoes.length=0;await sync();assert.ok(requisicoes.find(r=>r.call==='ListarMovimentos').param[0].dDtAltDe);assert.equal([...registros.keys()].filter(k=>k==='rec|rbomie-2025').length,1);console.log('OK recuar corte busca histórico completo, importa 2025 e retoma incremental sem duplicar');
for (const [body,headers,status] of [
 [{action:'sincronizar',automatico:true},{},401],
 [{action:'saude',automatico:true},{'x-rotina-token':'token'},401],
 [{action:'sincronizar',automatico:true},{'x-rotina-token':'token'},200],
]) {const r=await handler(new Request('https://teste.invalid',{method:'POST',headers,body:JSON.stringify(body)}));assert.equal(r.status,status);}
assert.equal(metas.get('omie_sync').por,'Automático · servidor');console.log('OK rotina exige segredo e autoriza somente sincronização; origem automática registrada');
assert.equal(metas.get('omie_sync').status,'completa');console.log('PASSOU integração Omie em memória');})().catch(e=>{console.error(e);process.exit(1)});
