const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const ctx=vm.createContext({TELAS:{}});
vm.runInContext(fs.readFileSync(path.join(__dirname,'../financeiro.js'),'utf8'),ctx);
const cor=(x,aba='')=>ctx.finCor(x,aba);
assert.equal(cor({tipo:'saida',vendaId:'v1'}),'fin-saida','Despesa ligada à venda continua sendo saída');
assert.equal(cor({cx:{tipo:'saida'},vendaId:'v1'}),'fin-saida');
assert.equal(cor({obrigacao:{},vendaId:'v1'}),'fin-saida');
assert.equal(cor({titulo:{grupo:'CONTA_A_PAGAR'},vendaId:'v1'}),'fin-saida');
assert.equal(cor({rec:{}}),'fin-entrada');
assert.equal(cor({cx:{tipo:'entrada'}}),'fin-entrada');
assert.equal(cor({},'despesas'),'fin-saida');
assert.equal(cor({},'pagar'),'fin-saida');
assert.equal(cor({},'receber'),'fin-entrada');
assert.equal(cor({transferencia:true,entrada:false}),'');
assert.equal(cor({entrada:false}),'fin-saida');
assert.equal(cor({entrada:true}),'fin-entrada');
assert.equal(cor({valor:-50}),'','Sinal de diferença sem origem não define receita ou despesa');
assert.equal(ctx.finCorTotal([{tipo:'saida'},{obrigacao:{}}]),'fin-saida');
assert.equal(ctx.finCorTotal([{tipo:'entrada'},{rec:{}}]),'fin-entrada');
assert.equal(ctx.finCorTotal([{tipo:'saida'},{tipo:'entrada'}]),'');
assert.equal(ctx.finCorTotal([{tipo:'saida'},{valor:10}]),'');
console.log('PASSOU: 17 classificações de cor, incluindo saídas vinculadas a vendas e transferências.');
