const {chromium}=require('/Users/leonardopereira/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const fs=require('fs'),path=require('path'),assert=require('assert/strict');
(async()=>{
const backup=JSON.parse(fs.readFileSync(process.env.BSQ_TEST_SNAPSHOT||'seed/backup-pre-publicacao.json'));
const browser=await chromium.launch({channel:'chrome',headless:true});const context=await browser.newContext({serviceWorkers:'block'});const page=await context.newPage();const erros=[];page.on('pageerror',e=>erros.push(e.message));
await context.route('**/*',async route=>{const req=route.request(),u=new URL(req.url());if(u.hostname==='bosques.test'){const file=path.resolve('.'+(u.pathname==='/'?'/index.html':u.pathname));if(!file.startsWith(process.cwd()+'/')||!fs.existsSync(file))return route.fulfill({status:404});let body=fs.readFileSync(file);if(u.pathname==='/config.js')body=Buffer.from(body.toString().replace('FINANCEIRO_EM_VALIDACAO = false','FINANCEIRO_EM_VALIDACAO = true'));return route.fulfill({body,contentType:u.pathname.endsWith('.js')?'text/javascript':u.pathname.endsWith('.css')?'text/css':u.pathname.endsWith('.png')?'image/png':'text/html'});}
let body={ok:true,sync:{status:'completa',quando:new Date().toISOString()},contas:[],registros:backup.registros,cfg:backup.cfg,eu:{perfil:'direcao',nome:'Teste',proprio:true,id:'teste'}};return route.fulfill({json:body});});
await context.addInitScript(()=>{localStorage.setItem('bsq_senha','teste');localStorage.setItem('bsq_quem','Teste');});
await page.goto('https://bosques.test/');await page.waitForFunction(()=>S.reg.venda.length>0);
const auditoria=await page.evaluate(()=>{
 const comercial=resumoComercial(),ar=aReceberPorMes(),aging=agingInadimplencia();
 const porVenda=vendasVivas().reduce((s,v)=>s+Math.round(resumoVenda(v).emAtraso*100),0)/100;
 const porAging=aging.reduce((s,x)=>s+Math.round(x.rs*100),0)/100;
 const ts=lista('titulo').filter(t=>t.grupo==='CONTA_A_RECEBER'&&t.status!=='CANCELADO'&&t.venc<hojeISO()&&Number(t.original?.resumo?.nValAberto)>0);
 return {em:new Date().toISOString(),comercial:{lotes:comercial.totalLotes,vendidos:comercial.vendidos,disponiveis:comercial.disponiveis,contratos:comercial.contratos.length,ativos:comercial.ativos,quitados:comercial.quitados,vgv:comercial.vgv,statusDivergentes:comercial.divergencias.length,contratosSemLote:comercial.semLote.length},atraso:{vendas:porVenda,relatorios:ar.vencido,aging:porAging,omie:ts.reduce((s,t)=>s+Math.round(Number(t.original.resumo.nValAberto)*100),0)/100,titulosOmie:ts.length,detalhe:ts.map(t=>({tid:t.titulo,venc:t.venc,valor:t.valor,saldoOmie:t.original.resumo.nValAberto,parcelas:lista('venda').flatMap(v=>resumoVenda(v).carne.filter(p=>String(p.tid)===String(t.titulo)).map(p=>({venda:v.codigo,situacaoVenda:v.situacao,saldo:p.saldo,situacao:p.situacao,conferir:p.conferir,valor:p.valor,valorDia:p.valorDia,desconto:p.desconto})))}))},atrasosLocais:lista('venda').flatMap(v=>resumoVenda(v).carne.filter(p=>p.situacao==='atrasada').map(p=>({venda:v.codigo,tid:p.tid,valor:p.valor,pago:p.pago,saldo:p.saldo,origem:lista('titulo').find(t=>String(t.titulo)===String(p.tid))?.original?.resumo}))),caixa:totaisAcumulados(),diferencas:finDiferencas().map(x=>({id:x.id,data:x.data,descricao:x.descricao,motivo:x.situacao,valor:x.valor}))};
});
fs.writeFileSync('seed/auditoria-telas.json',JSON.stringify(auditoria,null,2),{mode:384});
assert.ok(Math.abs(auditoria.atraso.omie-auditoria.atraso.relatorios)<0.01,'Atraso divergente entre origem e relatório');assert.ok(Math.abs(auditoria.atraso.vendas-auditoria.atraso.aging)<0.01,'Atraso divergente no aging');console.log(JSON.stringify({...auditoria,diferencas:auditoria.diferencas.length}));
for(const width of [1440,390]){await page.setViewportSize({width,height:950});for(const tela of ['home','espelho','vendas','simulador','contratos','propostas','financeiro','cronograma','clientes','corretores','apresentacao','config','caixa','lancamentos','relatorios']){await page.evaluate(t=>{location.hash='#/'+t;},tela);await page.waitForTimeout(120);const bad=await page.evaluate(()=>({over:document.documentElement.scrollWidth-innerWidth,text:document.querySelector('#app').innerText}));if(bad.over>1)console.log(await page.evaluate(()=>[...document.querySelectorAll('body *')].filter(e=>e.getBoundingClientRect().right>innerWidth+1).slice(0,20).map(e=>({tag:e.tagName,id:e.id,classe:e.className,width:e.getBoundingClientRect().width}))));assert.ok(bad.over<=1,`Largura excedida ${tela} ${width}: ${bad.over}`);assert.ok(!/NaN|undefined/.test(bad.text),'Valor inválido '+tela);console.log('OK '+tela+' '+width);}}
assert.deepEqual(erros,[]);await browser.close();console.log('PASSOU telas completas com cópia privada dos dados');
})().catch(e=>{console.error(e.message);process.exit(1)});
