const fs=require('fs'),assert=require('assert/strict');
const {PGlite}=require('../seed/devtools/node_modules/@electric-sql/pglite');
(async()=>{const db=new PGlite();await db.exec("create role anon;create role authenticated;create role service_role; create table bsq_registros(colecao text,id text,registro jsonb,atualizado_em timestamptz,primary key(colecao,id));");
await db.exec(fs.readFileSync('supabase/migrations/202609050001_vinculo_financeiro.sql','utf8'));
const put=async(c,id,r)=>db.query('insert into bsq_registros values($1,$2,$3,now())',[c,id,JSON.stringify(r)]);
await put('venda','a',{id:'a',clienteId:'123',parcelas:[{tid:'10',valor:500,venc:'2026-09-20'}]});await put('venda','b',{id:'b',clienteId:'123',parcelas:[]});await put('venda','c',{id:'c',clienteId:'456',parcelas:[]});await put('rec','r',{id:'r',vendaId:'a',valor:200,omie:{titulo:10}});
await assert.rejects(()=>db.query("select bsq_vincular_titulo('10','c','teste','documento conferido')"),/outro cliente/);
let antes=await db.query("select registro from bsq_registros where colecao='venda' and id='a'");assert.equal(antes.rows[0].registro.parcelas.length,1);console.log('OK rejeição por cliente preserva dados');
await db.query("select bsq_vincular_titulo('10','b','teste','documento conferido')");
let vendas=await db.query("select id,registro from bsq_registros where colecao='venda' order by id");assert.equal(vendas.rows[0].registro.parcelas.length,0);assert.equal(vendas.rows[1].registro.parcelas.length,1);
let rec=await db.query("select registro from bsq_registros where colecao='rec'");assert.equal(rec.rows[0].registro.vendaId,'b');assert.equal(rec.rows[0].registro.alocacoes[0].valor,200);console.log('OK vínculo move parcela e recebimento juntos');
await db.query("select bsq_vincular_titulo('10','b','teste','repetição')");vendas=await db.query("select registro from bsq_registros where colecao='venda' and id='b'");assert.equal(vendas.rows[0].registro.parcelas.length,1);console.log('OK repetição não duplica parcela');
await assert.rejects(()=>db.query("select bsq_vincular_titulo('99','b','teste','não existe')"),/não encontrado/);console.log('OK título inexistente não grava');await db.exec('create table bsq_cfg(id boolean primary key,config jsonb,atualizado_em timestamptz)');
await db.exec(fs.readFileSync('supabase/migrations/202609050002_centros_custo.sql','utf8'));
await db.query("select bsq_editar_centro('','Portaria','teste')");
await put('cx','custo',{id:'custo',valor:123.45,centroCusto:'Portaria'});
await db.query("select bsq_editar_centro('Portaria','Entrada principal','teste')");
const custo=(await db.query("select registro from bsq_registros where colecao='cx' and id='custo'")).rows[0].registro;
assert.equal(custo.centroCusto,'Entrada principal');assert.equal(custo.valor,123.45);
await assert.rejects(()=>db.query("select bsq_editar_centro('','Entrada principal','teste')"),/já existe/);
console.log('OK centro renomeado sem alterar valor; duplicado rejeitado');await db.close();})().catch(e=>{console.error(e.message);process.exit(1)});
