const fs=require('fs'),vm=require('vm'),assert=require('assert/strict'),ts=require('../seed/devtools/node_modules/typescript');
const clone=x=>JSON.parse(JSON.stringify(x));const registros=new Map(),metas=new Map();let handler,numero=0;
const key=(c,id)=>c+'|'+id;
registros.set(key('venda','v1'),{id:'v1',clienteId:'123',parcelas:[{tid:1,valor:625,venc:'2026-09-20',conferir:false}]});
registros.set(key('cx','manual'),{id:'manual',tipo:'saida',valor:100,data:'2026-09-05'});
const cfg={omie:{corteEntradas:'2026-01-01'}};
const dados={agora:()=>new Date().toISOString(),lerCfgBruta:async()=>clone(cfg),lerColecaoBruta:async c=>[...registros].filter(([k])=>k.startsWith(c+'|')).map(([,r])=>({registro:clone(r)})),lerUm:async(c,id)=>registros.has(key(c,id))?clone(registros.get(key(c,id))):null,
 gravarUm:async(c,id,r)=>registros.set(key(c,id),clone(r)),gravarVarios:async xs=>{for(const x of xs)registros.set(key(x.colecao,x.id),clone(x.registro));},marcarMudanca:async()=>{},registrarLog:async()=>{},guardarIndiceNumero:async()=>{},proximoNumero:async()=>++numero,
 db:{from:()=>({select(){return this},eq(k,v){this.k=v;return this},maybeSingle:async function(){return {data:metas.has(this.k)?{valor:clone(metas.get(this.k))}:null}},upsert:async function(x){metas.set(x.chave,clone(x.valor));return{error:null}},delete(){return this}})}};
let movimentos=[{detalhes:{nCodTitulo:1,cGrupo:'CONTA_A_RECEBER',cStatus:'RECEBIDO',nValorTitulo:625,cCPFCNPJCliente:'123',dDtVenc:'20/09/2026',dDtPagamento:'05/09/2026'},resumo:{cLiquidado:'S',nValPago:625,nValLiquido:500,nDesconto:125,nValAberto:0}}, {detalhes:{nCodTitulo:2,cGrupo:'CONTA_A_PAGAR',cStatus:'PAGO',nValorTitulo:100,dDtPagamento:'05/09/2026'},resumo:{cLiquidado:'S',nValPago:100}}];
const ctx={console,Request,Response,Date,Map,Set,JSON,Number,String,Object,Math,Promise,Deno:{env:{get:()=> 'token'},serve:f=>handler=f},exports:{},fetch:async(_u,o)=>{const b=JSON.parse(o.body);return new Response(JSON.stringify(b.call==='ListarClientes'?{clientes_cadastro:[],total_de_paginas:1}:{nTotPaginas:1,movimentos}),{status:200})},require:p=>p.includes('dados')?dados:p.includes('cors')?{json:(b,s=200)=>new Response(JSON.stringify(b),{status:s}),preflight:()=>null}:{identificar:async()=>({perfil:'direcao',proprio:true,nome:'Teste'}),perfilDe:q=>q.perfil}};
vm.createContext(ctx);vm.runInContext(ts.transpileModule(fs.readFileSync('supabase/functions/bsq-omie/index.ts','utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText,ctx);
const sync=async()=>{const r=await handler(new Request('https://teste.invalid',{method:'POST',headers:{'x-token':'token'},body:JSON.stringify({action:'sincronizar',completa:true})}));const b=await r.json();assert.equal(r.status,200,JSON.stringify(b));return b;};
(async()=>{await sync();assert.equal(registros.get('rec|rbomie-1').valor,500);assert.ok(!registros.has('cx|cxomie-2'));assert.ok(registros.has('titulo|CONTA_A_PAGAR-2'));assert.ok(registros.has('cx|manual'));assert.ok(metas.get('omie_sync').pendencias.some(p=>p.tipo==='possivel_duplicidade'));console.log('OK movimento igual preservado para conciliação sem duplicar caixa');registros.get('titulo|CONTA_A_PAGAR-2').decisaoDuplicidade='distintos';
await sync();assert.equal([...registros.keys()].filter(k=>k.startsWith('rec|')).length,1);console.log('OK repetição idempotente');
movimentos[0].resumo.nJuros=20;movimentos[0].resumo.nValLiquido=520;await sync();assert.equal(registros.get('rec|rbomie-1').valor,520);assert.equal(registros.get('rec|rbomie-1').omie.original.resumo.nValPago,625);console.log('OK valor líquido inclui desconto e juros preservando o principal');
const core=require('../financeiro-core.js');assert.equal(core.resumo(registros.get('venda|v1'),[registros.get('rec|rbomie-1')],'2026-10-01').saldo,0);console.log('OK encargos de parcela quitada não viram atraso');
movimentos[0].detalhes.cStatus='CANCELADO';movimentos[1].detalhes.cStatus='CANCELADO';await sync();assert.ok(registros.get('rec|rbomie-1').apagadoEm);assert.ok(registros.get('cx|cxomie-2').apagadoEm);console.log('OK estorno de receita e despesa');
movimentos=[{detalhes:{nCodTitulo:99,cGrupo:'CONTA_A_RECEBER',cCPFCNPJCliente:'123',cStatus:'ABERTO',nValorTitulo:625,dDtVenc:'20/10/2026'},resumo:{nValPago:0,nValAberto:625}}];await sync();assert.ok(registros.has('titulo|CONTA_A_RECEBER-99'));assert.ok(!registros.get('venda|v1').parcelas.some(p=>p.tid===99));assert.ok(metas.get('omie_sync').pendencias.some(p=>p.titulo===99));console.log('OK título novo preservado sem vínculo inventado');
assert.equal(metas.get('omie_sync').status,'completa');console.log('PASSOU integração Omie em memória');})().catch(e=>{console.error(e);process.exit(1)});
